apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: prod
type: Opaque
data:
  mongo-root-username: cm9vdA==  # base64 encoded value for 'root'
  mongo-root-password: cGFzc3dvcmQ=  # base64 encoded value for 'password'